language: java
addons:
  apt:
    packages:
      - openjdk-6-jdk
jdk:
    - openjdk7
    - openjdk8
    - oraclejdk9
    - oraclejdk11
branches:
    except:    
        - /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
install:
    - true
script:
    - mvn verify
