language: java
sudo: required
addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
    - oraclejdk8
    - oraclejdk7
    - openjdk6
branches:
    except:    
        - /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
install:
    - true
script:
    - mvn verify
